/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ValorMedio;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhosu
 */
public class InterfazValorMedio extends javax.swing.JFrame {
    
    DefaultTableModel mt = new DefaultTableModel();

    /**
     * Creates new form InterfazValorMedio
     */
    public InterfazValorMedio() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        String ids [] = {" X"," Y"};
        mt.setColumnIdentifiers(ids);
        jTable1.setModel(mt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logicaDerivada1 = new com.ValorMedio.LogicaDerivada();
        logicaFuncion1 = new com.ValorMedio.LogicaFuncion();
        principalBackground = new javax.swing.JPanel();
        jLabelTitlePrincipal = new javax.swing.JLabel();
        jButtonIngresoDatos = new javax.swing.JButton();
        jTextFieldFuncion = new javax.swing.JTextField();
        jLabelIngreseFuncion = new javax.swing.JLabel();
        Background2 = new javax.swing.JPanel();
        slogan = new javax.swing.JLabel();
        curso = new javax.swing.JLabel();
        Me = new javax.swing.JLabel();
        firstIntervalo = new javax.swing.JLabel();
        intervalo1 = new javax.swing.JTextField();
        BtnGraficar = new javax.swing.JButton();
        secondIntervalo = new javax.swing.JLabel();
        intervalo2 = new javax.swing.JTextField();
        showResultDeriva = new javax.swing.JTextField();
        derivada = new javax.swing.JLabel();
        resultFA = new javax.swing.JLabel();
        showResultFA = new javax.swing.JTextField();
        resultFB = new javax.swing.JLabel();
        showResultFB = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        funcionFC = new javax.swing.JLabel();
        showFuncionFC = new javax.swing.JTextField();
        limpiarPanel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        principalBackground.setBackground(new java.awt.Color(255, 255, 255));
        principalBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitlePrincipal.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelTitlePrincipal.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitlePrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitlePrincipal.setText("TEOREMA VALOR MEDIO");
        principalBackground.add(jLabelTitlePrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 330, 60));

        jButtonIngresoDatos.setBackground(new java.awt.Color(254, 148, 2));
        jButtonIngresoDatos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonIngresoDatos.setForeground(new java.awt.Color(204, 204, 204));
        jButtonIngresoDatos.setText("INGRESAR DATOS");
        jButtonIngresoDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresoDatosActionPerformed(evt);
            }
        });
        principalBackground.add(jButtonIngresoDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));
        principalBackground.add(jTextFieldFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 250, 30));

        jLabelIngreseFuncion.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIngreseFuncion.setText("INGRESE LA FUNCIÓN:");
        principalBackground.add(jLabelIngreseFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        Background2.setBackground(new java.awt.Color(29, 41, 72));

        slogan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        slogan.setForeground(new java.awt.Color(255, 255, 255));
        slogan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slogan.setText("Proyecto Valor Medio");

        curso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        curso.setForeground(new java.awt.Color(255, 255, 255));
        curso.setText("Cálculo I");

        Me.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Me.setForeground(new java.awt.Color(255, 255, 255));
        Me.setText("Alumno: Josué Hicho");

        javax.swing.GroupLayout Background2Layout = new javax.swing.GroupLayout(Background2);
        Background2.setLayout(Background2Layout);
        Background2Layout.setHorizontalGroup(
            Background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slogan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Background2Layout.createSequentialGroup()
                .addGroup(Background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Background2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(Me))
                    .addGroup(Background2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(curso)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        Background2Layout.setVerticalGroup(
            Background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background2Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(slogan, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(curso)
                .addGap(34, 34, 34)
                .addComponent(Me)
                .addContainerGap(397, Short.MAX_VALUE))
        );

        principalBackground.add(Background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 690));

        firstIntervalo.setForeground(new java.awt.Color(0, 0, 0));
        firstIntervalo.setText("PRIMER INTERVALO");
        principalBackground.add(firstIntervalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));
        principalBackground.add(intervalo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 60, 30));

        BtnGraficar.setBackground(new java.awt.Color(254, 148, 2));
        BtnGraficar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnGraficar.setForeground(new java.awt.Color(204, 204, 204));
        BtnGraficar.setText("TABLA DE VALORES");
        BtnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGraficarActionPerformed(evt);
            }
        });
        principalBackground.add(BtnGraficar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        secondIntervalo.setForeground(new java.awt.Color(0, 0, 0));
        secondIntervalo.setText("SEGUNDO INTERVALO");
        principalBackground.add(secondIntervalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));
        principalBackground.add(intervalo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 60, 30));
        principalBackground.add(showResultDeriva, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 170, 30));

        derivada.setForeground(new java.awt.Color(0, 0, 0));
        derivada.setText("DERIVADA:");
        principalBackground.add(derivada, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        resultFA.setForeground(new java.awt.Color(0, 0, 0));
        resultFA.setText("f(a):");
        principalBackground.add(resultFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, -1));

        showResultFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showResultFAActionPerformed(evt);
            }
        });
        principalBackground.add(showResultFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 50, 30));

        resultFB.setForeground(new java.awt.Color(0, 0, 0));
        resultFB.setText("f(b):");
        principalBackground.add(resultFB, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, -1, -1));
        principalBackground.add(showResultFB, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, 50, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        principalBackground.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 270, 80));

        funcionFC.setForeground(new java.awt.Color(0, 0, 0));
        funcionFC.setText("Función F(c):");
        principalBackground.add(funcionFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));
        principalBackground.add(showFuncionFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 170, 30));

        limpiarPanel.setBackground(new java.awt.Color(255, 153, 51));
        limpiarPanel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        limpiarPanel.setText("LIMPIAR");
        limpiarPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarPanelActionPerformed(evt);
            }
        });
        principalBackground.add(limpiarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresoDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresoDatosActionPerformed
        String funcion = jTextFieldFuncion.getText();
        
        double interva1 = Double.parseDouble(intervalo1.getText());
        
        double interva2 = Double.parseDouble (intervalo2.getText());
        
        //CREACION DE OBJETOS DE LA CLASE LogicaFuncion
        //ACCEDIENDO A LOS METODOS DEL OBJETO(LIBRERIA JEP)
        LogicaFuncion fun = new LogicaFuncion();
        fun.setFuncion(funcion);
        fun.setValorx(interva1);
        fun.evaluar();
        showResultFA.setText(fun.getResultadoFuncion() + "");
        double fa = fun.getResultadoFuncion();
        
        LogicaFuncion fun2 = new LogicaFuncion();
        fun2.setFuncion(funcion);
        fun2.setValorx(interva2);
        fun2.evaluar();
        showResultFB.setText(fun2.getResultadoFuncion() + "");
        double fb = fun2.getResultadoFuncion();
        
        
        //PASANDO LOS VALORES PARA LA FÓRMULA DE FC (Fb - Fa)/b-a
        double resultFC = fun.ecuacionVMedio(interva1, interva2, fb, fa);
        String resultadoFC = String.valueOf(resultFC);
        showFuncionFC.setText(resultadoFC);
        
        
        
        //CREACION DE OBJETO DE LA CLASE LogicaDerivada
        //ACCEDIENDO A LOS METODOS DEL OBJETO (LIBRERIA DJEP y jep) para resolver las derivadas
        LogicaDerivada derivada = new LogicaDerivada();
        derivada.setFuncionDerivar(funcion);
        derivada.derivar();
        showResultDeriva.setText(derivada.getFuncionDerivada());
        
        String derivadaC = derivada.getFuncionDerivada();
        LogicaFuncion funcionC = new LogicaFuncion();
        funcionC.recorrerDerivada(derivadaC);
        
//        double derivaC = Double.parseDouble(derivadaC);
//        System.out.println(derivaC);
        
    }//GEN-LAST:event_jButtonIngresoDatosActionPerformed

    private void BtnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGraficarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGraficarActionPerformed

    private void showResultFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showResultFAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showResultFAActionPerformed

    private void limpiarPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarPanelActionPerformed
        jTextFieldFuncion.setText("");
        intervalo1.setText("");
        intervalo2.setText("");
        showResultFA.setText("");
        showResultFB.setText("");
        showResultDeriva.setText("");
        showFuncionFC.setText("");
    }//GEN-LAST:event_limpiarPanelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazValorMedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazValorMedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazValorMedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazValorMedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazValorMedio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background2;
    private javax.swing.JButton BtnGraficar;
    private javax.swing.JLabel Me;
    private javax.swing.JLabel curso;
    private javax.swing.JLabel derivada;
    private javax.swing.JLabel firstIntervalo;
    private javax.swing.JLabel funcionFC;
    private javax.swing.JTextField intervalo1;
    private javax.swing.JTextField intervalo2;
    private javax.swing.JButton jButtonIngresoDatos;
    private javax.swing.JLabel jLabelIngreseFuncion;
    private javax.swing.JLabel jLabelTitlePrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldFuncion;
    private javax.swing.JButton limpiarPanel;
    private com.ValorMedio.LogicaDerivada logicaDerivada1;
    private com.ValorMedio.LogicaFuncion logicaFuncion1;
    private javax.swing.JPanel principalBackground;
    private javax.swing.JLabel resultFA;
    private javax.swing.JLabel resultFB;
    private javax.swing.JLabel secondIntervalo;
    private javax.swing.JTextField showFuncionFC;
    private javax.swing.JTextField showResultDeriva;
    private javax.swing.JTextField showResultFA;
    private javax.swing.JTextField showResultFB;
    private javax.swing.JLabel slogan;
    // End of variables declaration//GEN-END:variables
}
